version: '3.9'

services:
  pgsql:
    image: 'postgres:11.17-bullseye'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: '${PG_DB_NAME}'
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
    volumes:
      - 'sailpgsql:/var/lib/pgsql'

volumes:
  sailmysql:
    driver: local
  sailpgsql:
    driver: local
